server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:mybatis/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.yjiu.pojo
logging:
  level:
    root: info
